name: vregistration
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  provider: ^6.0.5
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  shared_preferences: ^2.1.1
  country_picker: ^2.0.20
  pinput: ^2.2.31
  excel: ^2.1.0
  cloud_firestore: ^4.7.1
  qr_code_scanner: ^1.0.1
  carousel_slider: ^4.2.1
  syncfusion_flutter_gauges: ^22.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
